name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - master    # Trigger workflow on push to the master branch

jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x to Build
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: CI=false npm run build

      - name: Transfer Build Folder on EC2 Instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.DEPLOY_TARGET }}
