name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - master    # Trigger workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'   # Specify the version of Node.js you want

      - name: Install dependencies
        run: |
          npm install

      - name: Build the React app
        run: |
          npm run build

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download production build
        uses: actions/download-artifact@v2
        with:
          name: react-build
          path: build/

      - name: Copy build files to EC2 instance
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_IP }}           # Store EC2 public IP in GitHub Secrets
          username: ec2-user                     # Replace with your EC2 username (ec2-user for Amazon Linux)
          key: ${{ secrets.EC2_PRIVATE_KEY }}    # Store your EC2 private key in GitHub Secrets
          port: 22
          source: "./build/*"
          target: "/usr/share/nginx/html"       # Path to Nginx HTML directory

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
