name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - master    # Trigger workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # Use a more recent LTS version

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Archive production build
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download production build
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build/

      - name: Copy build files to EC2 instance
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "/var/www/react-app"

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mv /var/www/react-app/* /usr/share/nginx/html/
            sudo systemctl restart nginx
